### ISSUE TITLE
setupTransitionOutTimeline conflicts with the transitionInTimeline

### ISSUE THREAD

**Issue by pigeonfresh** [larsvanbraam/vue-transition-component#9]
In my current project I've got a transition-page and transition-component (componentId="status-indicator)". The transitionInTimeline fades the page in, followed by a fade in of the child component. The transitionOutTimeline fades the component out and after that the page. The out transition works as expected. However: adding the timeline as the first instance of the out transition lets it conflict with the starting value of the In-transition.

See [gist](https://gist.github.com/pigeonfresh/360ca12e25426d35b8cc75c8c1cad04e)

**Comment by larsvanbraam** [comment]
It appears the problem here is the usage of fromTo on the transitionOutTimeline of your child component. When nesting timelines within other timelines you do not want to use fromTo, because this might cause weird jumps in the out animation. For example when the last known position of the component does not match the starting point of your transitionOutTimeline. 

Updated the code to throw an error when you use fromTo on a nested transitionOutTimeline!
